query AllCandles(
   $pageNumber: PageNumber!
   $pageSize: PageSize!
   $sort: CandlesSortEnum
   $filter: CandlesFilterInput
) {
   candles {
      allCandles(
         pageNumber: $pageNumber
         pageSize: $pageSize
         sort: $sort
         filter: $filter
      ) {
         __typename
         ... on VersionMismatchProblem {
            message
         }
         ... on InternalErrorProblem {
            message
         }
         ... on AllCandlesOk {
            candles {
               id
               title
               version
               color_id
               category_id
               images
               price
               slug
               description
               weight
            }
         }
      }
   }
}

query CandleById($input: CandlesByIdInput!) {
   candles {
      candleById(input: $input) {
         __typename
         ... on VersionMismatchProblem {
            message
         }
         ... on InternalErrorProblem {
            message
         }
         ... on CandlesByIdOk {
            candle {
               id
               title
               version
               color_id
               category_id
               images
               price
               slug
               description
               weight
            }
         }
      }
   }
}
