query AllColor {
   color {
      allColor {
         __typename
         ... on AllColorOk {
            colors {
               id
               title
               slug
            }
         }
         ... on VersionMismatchProblem {
            message
         }
         ... on InternalErrorProblem {
            message
         }
      }
   }
}

query ColorById($input: ColorByIdInput!) {
   color {
      colorById(input: $input) {
         ... on InternalErrorProblem {
            message
         }
         ... on VersionMismatchProblem {
            message
         }
         ... on ColorByIdOk {
            colors {
               id
               slug
               title
               version
            }
         }
      }
   }
}

mutation AddToColor($input: CreateColorInput!) {
   color {
      createColor(input: $input) {
         __typename
         ... on ColorCreateOk {
            id
         }
         ... on InternalErrorProblem {
            message
         }
         ... on UnauthorizedProblem {
            message
         }
         ... on VersionMismatchProblem {
            message
         }
      }
   }
}
