query UserById {
   user {
      profile {
         __typename
         ... on InternalErrorProblem {
            message
         }
         ... on VersionMismatchProblem {
            message
         }
         ... on UserProfileOk {
            profile {
               id
               role
            }
         }
      }
   }
}
